# Generated by Django 5.1.4 on 2024-12-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_tasks_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
