# Generated by Django 5.1.4 on 2024-12-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_daily_tasks_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
